version: '3.9'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=wishP0nd

  redis:
    image: redis:alpine
    restart: always

  test: &base
    build: .
    image: birthday_email-test
    command: bundle exec rspec -fd .
    volumes:
      - .:/birthday_email
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=test
      - REDIS_HOST=redis://redis:6379/0
    stdin_open: true
    tty: true

  web:
    <<: *base
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - REDIS_HOST=redis://redis:6379/0
  
